sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: a418ac94828a9c2b8fdc549db762845e0dc9f70e 
    on:
        branch: master
    local_dir: public
    repo: ottsion/ottsion.github.io
    target_branch: master
    email: emsunfc@163.com
    name: ottsion